apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-python
  labels:
    app: example-python
spec:
  selector:
    matchLabels:
      app: example-python
  template:
    metadata:
      labels:
        app: example-python
    spec:
      containers:
        - name: example-python
          image: example-python-image
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            limits:
              cpu: "500m"
              memory: "128Mi"
            requests:
              cpu: "250m"
              memory: "64Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
